COLUMN_MAP = {
    "A": "fulfillment_status",
    "B": "group_customer_name",
    "C": "account_name",
    "D": "domain",
    "E": "iou",
    "F": "sub_iou",
    "G": "country",
    "H": "branch",
    "I": "requirement_ageing_calendar_days",
    "J": "observation",
    "K": "primary_competency_proficiency_details",
    "L": "competency",
    "M": "experience_range",
    "N": "revenue_impact",
    "O": "onsite_offshore",
    "P": "won_sp",
    "Q": "delivery_manager",
    "R": "requirement_id",
    "S": "skill_manually_entered",
    "T": "added_date",
    "U": "service_practice",
    "V": "skill_consolidated",
    "W": "skill_consolidated_second_skill",
    "X": "fulfillment_perspective",
    "Y": "target_fulfillment_date",
    "Z": "revenue_at_risk",
    "AA": "revenue_won",
    "AB": "requirement_start_date",
    "AC": "candidate_name",
    "AD": "fulfillment_channel",
    "AE": "requirement_ageing_months",
    "AF": "pending_with",
    "AG": "gbams_rmg_name",
    "AH": "evaluator_emp_name",
    "AI": "evaluation_status",
    "AJ": "candidate_evaluation_stage",
    "AK": "sub_practice",
    "AL": "gbams_requirement_id",
    "AM": "sla_breach_days",
    "AN": "requirement_month",
    "AO": "it_bps",
}

REVERSE_COLUMN_MAP = {v: k for k, v in COLUMN_MAP.items()}

DERIVED_COLUMNS = {"I", "J", "P", "V", "W", "X", "AE", "AF", "AG", "AH", "AN", "AO"}
DERIVED_FIELDS = {COLUMN_MAP[c] for c in DERIVED_COLUMNS}

EDITABLE_FIELDS = {v for k, v in COLUMN_MAP.items() if k not in DERIVED_COLUMNS}
EDITABLE_FIELDS.discard("requirement_id")

HEADER_ALIASES: dict[str, str] = {
    "requirement id": "requirement_id",
    "req id": "requirement_id",
    "reqid": "requirement_id",
    "fulfillment status": "fulfillment_status",
    "fulfillmentstatus": "fulfillment_status",
    "group customer name": "group_customer_name",
    "customer name": "group_customer_name",
    "customername": "group_customer_name",
    "account name": "account_name",
    "accountname": "account_name",
    "account": "account_name",
    "domain": "domain",
    "iou": "iou",
    "sub iou": "sub_iou",
    "subiou": "sub_iou",
    "country": "country",
    "branch": "branch",
    "primary competency proficiency details": "primary_competency_proficiency_details",
    "competency": "competency",
    "experience range": "experience_range",
    "experience": "experience_range",
    "revenue impact": "revenue_impact",
    "revimpact": "revenue_impact",
    "onsite offshore": "onsite_offshore",
    "onsite/offshore": "onsite_offshore",
    "delivery manager": "delivery_manager",
    "deliverymanager": "delivery_manager",
    "skill": "skill_manually_entered",
    "primary skill": "skill_manually_entered",
    "manually entered skill": "skill_manually_entered",
    "added date": "added_date",
    "addeddate": "added_date",
    "service practice": "service_practice",
    "servicepractice": "service_practice",
    "target fulfillment date": "target_fulfillment_date",
    "target date": "target_fulfillment_date",
    "revenue at risk": "revenue_at_risk",
    "revenueatrisk": "revenue_at_risk",
    "revenue won": "revenue_won",
    "revenuewon": "revenue_won",
    "requirement start date": "requirement_start_date",
    "start date": "requirement_start_date",
    "candidate name": "candidate_name",
    "fulfillment channel": "fulfillment_channel",
    "evaluation status": "evaluation_status",
    "candidate evaluation stage": "candidate_evaluation_stage",
    "sub practice": "sub_practice",
    "gbams requirement id": "gbams_requirement_id",
    "sla breach days": "sla_breach_days",
    "observation": "observation",
    "won sp": "won_sp",
    "skill consolidated": "skill_consolidated",
    "fulfillment perspective": "fulfillment_perspective",
    "requirement ageing months": "requirement_ageing_months",
    "pending with": "pending_with",
    "gbams rmg name": "gbams_rmg_name",
    "evaluator emp name": "evaluator_emp_name",
    "requirement month": "requirement_month",
    "it/bps": "it_bps",
    "it bps": "it_bps",
}

OPEN_STATUSES = {"Open", "Pending", "In Progress", "Under Evaluation", "Recommended"}
FULFILLED_STATUSES = {"Fulfilled", "Closed Won"}

FULFILLMENT_FUNNEL_ORDER = [
    "Open Requirement",
    "Recommended",
    "Under Evaluation",
    "Approved",
    "Fulfilled",
]
